### ISSUE TITLE
division by zero error

### ISSUE THREAD

**Issue by amiltonwong** [HuguesTHOMAS/KPConv#10]
Hi, @HuguesTHOMAS 

When I run `python training_Semantic3D.py`, I got the following error:
```
Initiating input pipelines
2019-05-22 21:55:09.646196: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-05-22 21:55:09.810266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 980 Ti major: 5 minor: 2 memoryClockRate(GHz): 1.2405
pciBusID: 0000:01:00.0
totalMemory: 5.93GiB freeMemory: 5.10GiB
2019-05-22 21:55:09.810299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0, compute capability: 5.2)
Calib Neighbors 00000000 : timings 1386.89 21.57
Calib Neighbors 00000003 : timings 759.88 20.74
Calib Neighbors 00000011 : timings 131.92 18.18


Traceback (most recent call last):
  File "training_Semantic3D.py", line 213, in <module>
    dataset.init_input_pipeline(config)
  File "/data/code9/KPConv/datasets/common.py", line 710, in init_input_pipeline
    gen_function, gen_types, gen_shapes = self.get_batch_gen('training', config)
  File "/data/code9/KPConv/datasets/Semantic3D.py", line 457, in get_batch_gen
    random_pick_n = int(np.ceil(epoch_n / (self.num_training * (config.num_classes))))
ZeroDivisionError: division by zero

```

Any hints to fix this problem?

THX!

**Comment by HuguesTHOMAS** [comment]
#7

**Comment by HuguesTHOMAS** [comment]
Hi @amiltonwong ,

I found some mistakes in the Semantic3D.py file and corrected it. If you delete your data folders (except the original data folder), and start from the begining with the new Semantic3D.py file, it should work.

Best,
Hugues

**Comment by amiltonwong** [comment]
Hi, @HuguesTHOMAS,

Thanks for your reply. I git pull the updated version and create a new `Data` folder again. I still got the following error:  `ZeroDivisionError: division by zero`
(My tensorflow version is 1.12)

```
root@milton-ThinkCentre-M93p:/data/code10/KPConv# python training_Semantic3D.py 

Dataset Preparation
*******************
Preparation of sg27_station10_rgb_intensity-reduced
Preparation of birdfountain_station1_xyz_intensity_rgb
Preparation of castleblatten_station1_intensity_rgb
Preparation of castleblatten_station5_xyz_intensity_rgb
Preparation of marketplacefeldkirch_station1_intensity_rgb
Preparation of marketplacefeldkirch_station4_intensity_rgb
Preparation of MarketplaceFeldkirch_Station4_rgb_intensity-reduced
Preparation of marketplacefeldkirch_station7_intensity_rgb
Preparation of sg28_Station2_rgb_intensity-reduced
Preparation of stgallencathedral_station1_intensity_rgb
Preparation of stgallencathedral_station3_intensity_rgb
Preparation of stgallencathedral_station6_intensity_rgb
Preparation of StGallenCathedral_station6_rgb_intensity-reduced

Preparing KDTree for all scenes, subsampled at 0.060
[##############################] 100.0%

Preparing reprojection indices for validation and test
[##############################] 100.0%

Initiating input pipelines
WARNING:tensorflow:From /data/code10/KPConv/datasets/common.py:1031: calling reduce_min (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-05-31 01:57:12.293282: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-31 01:57:15.000023: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-05-31 01:57:15.187915: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
totalMemory: 11.91GiB freeMemory: 11.25GiB
2019-05-31 01:57:15.187952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-05-31 01:57:29.706400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-31 01:57:29.706429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-05-31 01:57:29.706435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-05-31 01:57:29.723432: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10886 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:01:00.0, compute capability: 6.1)
Calib Neighbors 00000000 : timings 11403.43 51.39
Calib Neighbors 00000001 : timings 4745.83 13.64
Calib Neighbors 00000002 : timings 4939.09 17.02
Calib Neighbors 00000003 : timings 8167.17 15.69
Calib Neighbors 00000004 : timings 9827.12 13.57
Calib Neighbors 00000005 : timings 5139.68 13.81
Calib Neighbors 00000006 : timings 3433.58 16.71
Calib Neighbors 00000007 : timings 2194.88 15.58
Calib Neighbors 00000008 : timings 2937.20 13.77
Calib Neighbors 00000009 : timings 1491.37 16.82
Calib Neighbors 00000011 : timings 739.47 17.98
Calib Neighbors 00000012 : timings 1339.00 18.13
Calib Neighbors 00000013 : timings 1188.84 15.59
Calib Neighbors 00000014 : timings 1317.37 16.01


Traceback (most recent call last):
  File "training_Semantic3D.py", line 213, in <module>
    dataset.init_input_pipeline(config)
  File "/data/code10/KPConv/datasets/common.py", line 710, in init_input_pipeline
    gen_function, gen_types, gen_shapes = self.get_batch_gen('training', config)
  File "/data/code10/KPConv/datasets/Semantic3D.py", line 462, in get_batch_gen
    random_pick_n = int(np.ceil(epoch_n / (self.num_training * (config.num_classes))))
ZeroDivisionError: division by zero

```

**Comment by amiltonwong** [comment]
supplement: During the running the `training_Semantic3D.py`
13 ply files are generated at `Data/Semantic3D/ply_full/reduced-8`
Any hints to fix this issue?

**Comment by HuguesTHOMAS** [comment]
Considering the files that you generated, I think the error comes from the fact that you did not download the whole dataset, and in particular the label files.
In the `original_data` folder, you should have :
* 19 files called `XXXX.txt`, which contain the points of all clouds
* 15 files called `XXXX.labels`, which contain the labels of the training clouds

Then the data pre-processing should create 15 ply files in `Data/Semantic3D/ply_subsampled/train` (the training folder), and 4 ply files in `Data/Semantic3D/ply_full/reduced-8` (the test folder). Given that all your plys are in the test folder, it means that the script cannot find the `XXXX.labels` files

**Comment by amiltonwong** [comment]
@HuguesTHOMAS , thanks for your reply. You're right, the training can run smoothly after re-arranging the data and label files.
