### ISSUE TITLE
Problem during training using Semantic3D

### ISSUE THREAD

**Issue by Essxnce** [HuguesTHOMAS/KPConv#23]
Hello,
When I tried to operate training using Semantic3D, I got an error like below:

-

(tensorflow) C:\Users\plati\Desktop\KPConv>python training_Semantic3D.py
Traceback (most recent call last):
  File "training_Semantic3D.py", line 39, in <module>
    from datasets.Semantic3D import Semantic3DDataset
  File "C:\Users\plati\Desktop\KPConv\datasets\Semantic3D.py", line 46, in <module>
    from datasets.common import Dataset
  File "C:\Users\plati\Desktop\KPConv\datasets\common.py", line 34, in <module>
    tf_neighbors_module = tf.load_op_library('tf_custom_ops/tf_neighbors.so')
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: tf_custom_ops\tf_neighbors.so not found

-

...and I don't know why. How can I solve it?

**Comment by HuguesTHOMAS** [comment]
Hello @Essxnce,

It seems that the custom tensorflow operator `tf_neighbors.so` is not compiled.

Have you followed every step in `INSTALL.md`? In particular the installation of our customized Tensorflow operators?

Did the command line `sh compile_op.sh` output any message?

Best,
Hugues
