### ISSUE TITLE
Errors when running the training_Semantic3D.py script

### ISSUE THREAD

**Issue by Violetit** [HuguesTHOMAS/KPConv#34]
Hi @HuguesTHOMAS 

Before I run the `training_Semantic3D.py` script,  I modified the `Semantic3D.py`  script like below:
` # Path of the folder containing ply files
        self.path = 'Data/Semantic3D'

        # Original data path
        self.original_folder = 'original_data'

        # Path of the training files
        # self.train_path = join(self.path, 'ply_subsampled/train')
        # self.test_path = join(self.path, 'ply_subsampled/reduced-8')
        self.train_path = join(self.path, self.original_folder)
        self.test_path = join(self.path, self.original_folder)
        # self.test_path = join(self.path, 'ply_subsampled/semantic-8')`

Then I run the `training_Semantic3D.py` script, The program reports an error as follows ：
`Calib Neighbors 00000000 : timings 20936.74 18.95
Calib Neighbors 00000001 : timings 3209.54 19.80
Calib Neighbors 00000002 : timings 2743.98 13.21
Calib Neighbors 00000005 : timings 18005.47 21.91
Calib Neighbors 00000008 : timings 2674.94 16.44
Calib Neighbors 00000009 : timings 5039.95 15.20
Calib Neighbors 00000011 : timings 3139.28 17.42
Calib Neighbors 00000013 : timings 2356.07 16.96

Traceback (most recent call last):
  File "training_Semantic3D.py", line 213, in <module>
    dataset.init_input_pipeline(config)
  File "/disk/tia/tia/KPConv/datasets/common.py", line 710, in init_input_pipeline
    gen_function, gen_types, gen_shapes = self.get_batch_gen('training', config)
  File "/disk/tia/tia/KPConv/datasets/Semantic3D.py", line 458, in get_batch_gen
    random_pick_n = int(np.ceil(epoch_n / (self.num_training * (config.num_classes))))
ZeroDivisionError: division by zero`

It seems that the `config.num_classes` is zero, and the value was not overwritten by dataset class when initiating input pipeline. 
Can you help me to solve this problem?
Waiting for your reply!

**Comment by HuguesTHOMAS** [comment]
Hi @Violetit,

I don't understand why you made these modifications. You need separate paths for the original data (unprocessed) and the input data (processed to be used by our framework). I think the bug just happens because you broke the dataset preparation by changing the code. I explained how the dataset should be prepared in details [here].(https://github.com/HuguesTHOMAS/KPConv/issues/31#issuecomment-544866485)

If you need more explanations, feel free to ask.

Best,
Hugues

**Comment by HuguesTHOMAS** [comment]
Hi @Violetit,

There was a mistake in the code and I just corrected it. It should work fine now.

Best,
Hugues
