### ISSUE TITLE
question about running "training_Semantic3D.py"

### ISSUE THREAD

**Issue by amiltonwong** [HuguesTHOMAS/KPConv#7]
Hi, @HuguesTHOMAS ,

When I run `python training_Semantic3D.py`, I got the following error:

```
Dataset Preparation
*******************
sg27_station10_rgb_intensity-reduced already done

birdfountain_station1_xyz_intensity_rgb already done

castleblatten_station1_intensity_rgb already done

castleblatten_station5_xyz_intensity_rgb already done

marketplacefeldkirch_station1_intensity_rgb already done

marketplacefeldkirch_station4_intensity_rgb already done

MarketplaceFeldkirch_Station4_rgb_intensity-reduced already done

marketplacefeldkirch_station7_intensity_rgb already done

sg28_Station2_rgb_intensity-reduced already done

stgallencathedral_station1_intensity_rgb already done

stgallencathedral_station3_intensity_rgb already done

stgallencathedral_station6_intensity_rgb already done

StGallenCathedral_station6_rgb_intensity-reduced already done


Preparing KDTree for all scenes, subsampled at 0.060
Traceback (most recent call last):
  File "training_Semantic3D.py", line 210, in <module>
    dataset.load_subsampled_clouds(dl0)
  File "/data/code9/KPConv/datasets/Semantic3D.py", line 289, in load_subsampled_clouds
    sub_labels = data['class']
ValueError: no field of name class

```

In line [289](https://github.com/HuguesTHOMAS/KPConv/blob/master/datasets/Semantic3D.py#L289) of Semantic3D.py, data is considered as dict. However, when I debug into the code, data is actually a numpy array, and its shape is` (1034819,) `. Could you give some suggestions to fix this issue?

THX!

**Comment by HuguesTHOMAS** [comment]
Hi @amiltonwong ,

I found some mistakes in the `Semantic3D.py` file and corrected it. If you delete your data folders (except the original data folder), and start from the begining with the new `Semantic3D.py` file, it should work. 

Best,
Hugues
